### ISSUE TITLE
[FEAT] ERD 기반의 entity 생성

### ISSUE THREAD

**Issue by for2ver0** [Despereaux-MAU/team-musubi#3]
- member
- store
- menu
- review
- order
- order_menu

**Comment by for2ver0** [comment]
[추가 논의된 사항]
- Entity에는 공통된 필드만 놔두고, service는 Service단에서 구현

**Comment by Eun-0** [comment]
[추가 논의된 사항]
- Entity에는 공통된 필드만 놔두고, service는 Service단에서 구현
